name: CNRS-AIST JRL
# Note: GitHub only supports pygments, while rouge is the default highlighter.
# Thus, we comment it and simply rely on the default highlighter.
# highlighter: pygments
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'vendor']
index_name: index_en.html
