name: CNRS-AIST JRL
# Note: GitHub only supports pygments, while rouge is the default highlighter.
# Thus, we comment it and simply rely on the default highlighter.
# highlighter: pygments
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-multiple-languages-plugin
exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'vendor']
languages: ["en", "jp"]
exclude_from_localizations: ["assets", "css", "font-awesome", "fonts", "js"]
default_locale_in_subfolder: true
